---
title: "Clustering II attempt2"
output: html_notebook
---

Install packages
```{r}
install.packages("imager", dependencies=TRUE)
install.packages("ggplot2")
```

load the image
```{r}
library("imager")
# store image data in variable.
img <- load.image("showmewhatugot.png")
# show image via Rstudio
img

```

```{r}
# show data structure
dim(img)
# covert img to data frame
imgFrame <- as.data.frame(img)
# show columns after conversion to dataframe with some data
head(imgFrame)

# expand the dataframe
imgPivot <- reshape(imgFrame,direction="wide",timevar = "cc",idvar = c("x","y"))

# show the change in the data frame with the extension of 3 columns
head(imgPivot)

# rename the columns
names(imgPivot)[3] <- "R"
names(imgPivot)[4] <- "G"
names(imgPivot)[5] <- "B"

# show columns with name change
head(imgPivot)
```

```{r}
library("ggplot2")

# create a map for use with graph tool to assist with plotting the image in a graph.
imageColor <- rgb(imgPivot[c("R", "G", "B")])
# plot the image using imageColor as the reference.
ggplot(data = imgPivot, aes(x = x, y = y)) + 
  geom_point(colour = imageColor) +
  coord_fixed()
```

```{r}
# Kmeans the image data using the R,G,B columns and add to the dataframe
kClusters <- 5
kMeansResult <- kmeans(imgPivot[c("R", "G", "B")], centers = kClusters)
kMeansResult$center
imgPivot$cluster <- kMeansResult$cluster
```

```{r}
# identify and assign a colour to the clusters, display in a chart.
clusterColours = rgb(kMeansResult$center)
plot(0, type="n", axes=FALSE, ylab="", xlab="", ylim=c(2,0), xlim=c(0,5))
title("Clusters as colours")

rect(0,0,1,1,col='#ffde00')
rect(1,0,2,1,col='#1c142d')

for (i in 0:(kClusters-1)) {
  rect(i,0,i+1,1,col=clusterColours[i+1])
}

text(0.5,0.5,'1')

SetTextContrastColor <- function(color)
{
  ifelse( mean(col2rgb(color)) > 127, "black", "white")
}

text(0.5,0.5,'1', col=SetTextContrastColor('#FDF700'))

##

#install.packages("plotly")
library("plotly")

imgPivotSample <- imgPivot[sample(1:nrow(imgPivot), 1000, replace=FALSE),]

plot <- plot_ly(
    imgPivotSample, x = ~R, y = ~G, z = ~B,
    color = ~cluster, colors = clusterColours,
    marker = list(symbol = "circle", size = 4)
  ) %>%
  add_markers() %>%
  layout(
    scene = list(xaxis = list(title = 'Red', color='#FF0000'),
                 yaxis = list(title = 'Green', color='#00FF00'),
                 zaxis = list(title = 'Blue', color='#0000FF'))
  )

plot

```

```{r}
kClustersMax <- 10
wss <- sapply(1:kClustersMax,
        function(k){kmeans(imgPivot[c("R", "G", "B")], k)$tot.withinss})
plot(1:kClustersMax, wss,
       type="b", pch = 19, frame = FALSE,
       xlab="Number of clusters K",
       ylab="Total within-clusters sum of squares")
#Makes a vertical line at 3
abline(v = 3, lty =2)

```

```{r}
kMeansResult$centers[imgPivot$cluster,]
kColours <- rgb(kMeansResult$centers[imgPivot$cluster,])
ggplot(data = imgPivot, aes(x = x, y = -y)) +  geom_point(colour = kColours) + coord_fixed()
```

```{r}
clusterLabel <-  2

grey_scale <- function(colour){
    grey <- colour[1] * 0.2126 + colour[2] * 0.7152 + colour[3] * 0.0722
    return(rgb(grey,grey,grey))
}

color_or_grey <- function(row){
  if(row["cluster"]==clusterLabel){
    return(rgb(row["R"],row["G"],row["B"]))
  }
  else{
    return(grey_scale(as.numeric(row[c("R","G","B")])))
  }
}


imgPivot$splash <- apply(imgPivot,1,color_or_grey)

ggplot(data = imgPivot, aes(x = x, y = -y)) +  geom_point(colour = imgPivot$splash) + coord_fixed()
```



